# Generated by Django 2.2.6 on 2019-10-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'stocks',
                'verbose_name': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='iame')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django-inventory-app.Stock', verbose_name='box')),
            ],
            options={
                'verbose_name_plural': 'items',
                'verbose_name': 'item',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django-inventory-app.Item', verbose_name='item')),
            ],
            options={
                'verbose_name_plural': 'images',
                'verbose_name': 'image',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django-inventory-app.Stock', verbose_name='stock')),
            ],
            options={
                'verbose_name_plural': 'boxes',
                'verbose_name': 'box',
            },
        ),
    ]
